export const SEND_MRI_REQUEST_STARTED = 'SEND_MRI_REQUEST_STARTED';
export const SEND_MRI_REQUEST_SUCCESS = 'SEND_MRI_REQUEST_SUCCESS';
export const SEND_MRI_REQUEST_FAILURE = 'SEND_MRI_REQUEST_FAILURE';