export const GET_SYNONYMS_STARTED = 'GET_SYNONYMS_STARTED';
export const GET_SYNONYMS_SUCCESS = 'GET_SYNONYMS_SUCCESS';
export const GET_SYNONYMS_FAILURE = 'GET_SYNONYMS_FAILURE';
export const ADD_SYNONYM = 'ADD_SYNONYM';
export const MODIFY_SYNONYM = 'MODIFY_SYNONYM';
export const DELETE_SYNONYM = 'DELETE_SYNONYM';
export const CHANGE_SYNONYM_SORT = 'CHANGE_SYNONYM_SORT';