curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4980\", \"DOB\": \"1996-12-12\", \"Height\": \"158\", \"inch-cm\": \"CM\", \"Weight\": \"67\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"rule out mass associated with L basal ganglia ICH sept 2019\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4980.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4981\", \"DOB\": \"1997-01-16\", \"Height\": \"159\", \"inch-cm\": \"CM\", \"Weight\": \"68\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"R/a CNS glioma\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4981.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4982\", \"DOB\": \"1997-02-20\", \"Height\": \"160\", \"inch-cm\": \"CM\", \"Weight\": \"69\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"Stuttering dysphagia; amyloid angiopathy\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4982.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4983\", \"DOB\": \"1997-03-27\", \"Height\": \"161\", \"inch-cm\": \"CM\", \"Weight\": \"70\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"RIGHT TENTORIAL MENINGIOMA. QUERY GROTH\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4983.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4984\", \"DOB\": \"1997-05-01\", \"Height\": \"162\", \"inch-cm\": \"CM\", \"Weight\": \"71\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"R/O OTHER SILENT STROKES\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4984.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4985\", \"DOB\": \"1997-06-05\", \"Height\": \"163\", \"inch-cm\": \"CM\", \"Weight\": \"72\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"SEIZURE PROTOCOL\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4985.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4986\", \"DOB\": \"1997-07-10\", \"Height\": \"164\", \"inch-cm\": \"CM\", \"Weight\": \"73\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"multiple unusual brain lesions in a young patient, needs urgent brain biopsy, for navigation purposes\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4986.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4987\", \"DOB\": \"1997-08-14\", \"Height\": \"165\", \"inch-cm\": \"CM\", \"Weight\": \"74\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"RIGHT CHRONIC OTITIS MEDIA. QUERY ANY RESIDUAL CHOLESTEATOMA IN CAVITY\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4987.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4988\", \"DOB\": \"1997-09-18\", \"Height\": \"166\", \"inch-cm\": \"CM\", \"Weight\": \"75\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"L sided facial numbness - ? sensory seizure vs migraine vs TIA - several ED visits and scan suggested by Dr. Dommann\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4988.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4989\", \"DOB\": \"1997-10-23\", \"Height\": \"167\", \"inch-cm\": \"CM\", \"Weight\": \"76\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"Dysarthria. Rule out recent stroke\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4989.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4990\", \"DOB\": \"1997-11-27\", \"Height\": \"168\", \"inch-cm\": \"CM\", \"Weight\": \"77\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"QUERY MENINGIOMA VS MALIGNANCY\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4990.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4991\", \"DOB\": \"1998-01-01\", \"Height\": \"169\", \"inch-cm\": \"CM\", \"Weight\": \"78\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"77F pontine hemorrhage - now having L-UE chorieform movements - r/o R-hemispheric lesion\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4991.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4992\", \"DOB\": \"1998-02-05\", \"Height\": \"170\", \"inch-cm\": \"CM\", \"Weight\": \"79\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"preop planning\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4992.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4993\", \"DOB\": \"1998-03-12\", \"Height\": \"171\", \"inch-cm\": \"CM\", \"Weight\": \"80\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"Follow up enhancemnet of Right facial nerve within temporal bone and parotid\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4993.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4994\", \"DOB\": \"1998-04-16\", \"Height\": \"172\", \"inch-cm\": \"CM\", \"Weight\": \"81\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"HIV POSITIVE\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4994.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4995\", \"DOB\": \"1998-05-21\", \"Height\": \"173\", \"inch-cm\": \"CM\", \"Weight\": \"82\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"FOLLOW UP\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4995.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4996\", \"DOB\": \"1998-06-25\", \"Height\": \"174\", \"inch-cm\": \"CM\", \"Weight\": \"83\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"QUERY CEREBRAL AVMS\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4996.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4997\", \"DOB\": \"1998-07-30\", \"Height\": \"175\", \"inch-cm\": \"CM\", \"Weight\": \"84\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"cp angle mass\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4997.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4998\", \"DOB\": \"1998-09-03\", \"Height\": \"176\", \"inch-cm\": \"CM\", \"Weight\": \"85\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"focal frontal headache, brain MRI showed enlargement of left foramen ovale possibly due to underlying nerve sheat tumor of V3 division of the fifth cranial nerve\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4998.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"4999\", \"DOB\": \"1998-10-08\", \"Height\": \"177\", \"inch-cm\": \"CM\", \"Weight\": \"86\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"FOLLOW UP RIGHT PARIETAL OLIGO-PAST RESECTION, NO ADJUVANT TX - ASSESS FOR RECURRENCE/PROGRESSION\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\4999.log
curl -H "Content-Type: application/json" -d "{\"cognito_user_fullname\": \"Ken LOCAL cmd\", \"ReqCIO\": \"5000\", \"DOB\": \"1998-11-12\", \"Height\": \"178\", \"inch-cm\": \"CM\", \"Weight\": \"87\", \"kg-lbs\": \"KG\", \"Radiologist Priority\": \"\", \"Reason for Exam\": \"R/o recurrent CNS disease - c/w BCCA and VGH scans\", \"Exam Requested\": \"MRI Head w/ Contrast\" }" http://127.0.0.1:5000/parser > logs\5000.log
